- cmd: |
    export SB_STYLE=sh
    { nix run --inputs-from . src-block < aifd; } 1<> aifd
  required_files:
  - aifd
  - usage.txt
  sha: 7f97239bd52da9aa12e8415dce06c9941a9213824376075867659533cc6942c4
- cmd: |
    export SB_STYLE=md
    { nix run --inputs-from . src-block < README.md; } 1<> README.md
  required_files:
  - README.md
  - usage.txt
  sha: 07834450c148bc0a41aeb14d1e83f9065d74c4ae4acec6b00e5270518498cf50
