- cmd: |
    export SB_STYLE=sh
    { nix run --inputs-from . src-block < aifd; } 1<> aifd
  required_files:
  - aifd
  - usage.txt
  sha: 810f518ebeec442876c7cc36b67342d9833285b87044bd279f9f5ced40cc8cbf
- cmd: |
    export SB_STYLE=md
    { nix run --inputs-from . src-block < README.md; } 1<> README.md
  required_files:
  - README.md
  - usage.txt
  sha: e7a3bc4e6926fc9cd4b46ec819605eadc8a4f4c8b1ebbb44a3b3a184ae4e9fb3
